export const iconsMap = {
  '@assets/images/abuso.png': require('@assets/images/abuso.png'),
  '@assets/images/acoso.png': require('@assets/images/acoso.png'),
  '@assets/images/alert.png': require('@assets/images/alert.png'),
  '@assets/images/close.png': require('@assets/images/close.png'),
  '@assets/images/comisaria.png': require('@assets/images/comisaria.png'),
  '@assets/images/drogas.png': require('@assets/images/drogas.png'),
  '@assets/images/estafa.png': require('@assets/images/estafa.png'),
  '@assets/images/gun.png': require('@assets/images/gun.png'),
  '@assets/images/homicidio_asesinato.png': require('@assets/images/homicidio_asesinato.png'),
  '@assets/images/homicidio_por_arma_de_fuego.png': require('@assets/images/homicidio_por_arma_de_fuego.png'),
  '@assets/images/hurto.png': require('@assets/images/hurto.png'),
  '@assets/images/hurto_agravado.png': require('@assets/images/hurto_agravado.png'),
  '@assets/images/hurto_agravado_casa_habitada.png': require('@assets/images/hurto_agravado_casa_habitada.png'),
  '@assets/images/hurto_frustrado.png': require('@assets/images/hurto_frustrado.png'),
  '@assets/images/hurto_vehiculo.png': require('@assets/images/hurto_vehiculo.png'),
  '@assets/images/microphone.png': require('@assets/images/microphone.png'),
  '@assets/images/robo.png': require('@assets/images/robo.png'),
  '@assets/images/robo_agravado.png': require('@assets/images/robo_agravado.png'),
  '@assets/images/robo_agravado_mano_armada.png': require('@assets/images/robo_agravado_mano_armada.png'),
  '@assets/images/robo_frustrado.png': require('@assets/images/robo_frustrado.png'),
  '@assets/images/robo_noche_desolado.png': require('@assets/images/robo_noche_desolado.png'),
  '@assets/images/robo_vehiculo.png': require('@assets/images/robo_vehiculo.png'),
  '@assets/images/secuestro.png': require('@assets/images/secuestro.png'),
};
